cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - yarn lint
  - yarn build
  - yarn test:api
  - yarn test --silent --coverage --coverageReporters=text-lcov | coveralls ; test ${PIPESTATUS[0]} -eq 0
before_deploy:
  - npm install --global gitbook-cli lerna
deploy:
  provider: script
  skip_cleanup: true
  script: yarn update-docs --scope=abi,light.js && ./scripts/lerna-publish.sh
  on:
branch: master
